### ISSUE TITLE
Wifi SSID & Password

### ISSUE THREAD

**Issue by mike-rankin** [neptune2/esp8266-weather-station-oled-DST#1]
There is no place to enter the wifi ssdid and password. How is it supposed to connect to wifi?

**Comment by neptune2** [comment]
There are 2 different ways:

**1:** Uncomment Line 252 in the esp8266-weather-station-oled-DST.ino file to use WiFiManager:

```
251:  // Uncomment for testing wifi manager
252:  wifiManager.resetSettings();
```

Remember to comment this line out, recompile and upload again after successfully setting SSID and PASSWORD in browser
See [WiFiManager Library](https://github.com/tzapu/WiFiManager) for more details on using WiFiManager.

**2:** Alternately, uncomment Line 259 to set an SSID and PASSWORD:

```
258:  //Manual Wifi
259:  WiFi.begin(SSID, PASSWORD);
```

**Comment by mike-rankin** [comment]
I added #define SSID "My SSID"   and  #define PASS "My PASSWORD"  to the top, uncommented wifiManager.resetSettings(); but still no luck. It hangs at the screen with 'connect to AP & random numbers.

**Comment by IoTMike** [comment]
I was able to manually set it uncommenting line 259 as noted above. I comment out the following lines (basically eliminate all references to WiFiManager):

```
55:  //#include <WiFiManager.h>
202: //void configModeCallback (WiFiManager *myWiFiManager);
250: //  WiFiManager wifiManager;
253: //  wifiManager.setAPCallback(configModeCallback);
256: //  wifiManager.autoConnect();
333: /* void configModeCallback (WiFiManager *myWiFiManager) {
...thru line 346: */ }
```

**Comment by Andrew252010** [comment]
Hello. I made a weather station according to your code and scheme. But the bmp images are not displayed. Only empty places. With the code from squix78, too, the icons are not visible. I get data from the weather server. BMP files are loaded. I tried to format SPIFFS, but it does not help.
Everything worked. Here is the answer. https://github.com/squix78/esp8266-weather-station-color/issues/10

**Comment by neptune2** [comment]
@Andrew252010 Your entry is in the wrong project (this is the OLED version - not the color LCD version). Also, please open a new issue instead of posting out-of-context to an existing issue.
Please open a new issue in https://github.com/neptune2/esp8266-weather-station-color-DST/issues
